with reference_data as
(SELECT
A.LOADNUMBER
,MDM.PARTYCODE::string partycode
,RN.VALUE::string AS REFNUM
FROM CDC_ORION.BROKER.EP_ACTIVITY AS A 
INNER JOIN CDC_ORION.BROKER.CO_ORDER AS O ON O.CUSTOMERORDERNUMBER = A.ORDERNUMBER AND O.HVR_ISDELETE = 0
INNER JOIN CDC_ORION.BROKER.CO_ORDERPARTY AS OP ON OP.CUSTOMERORDERID = O.CUSTOMERORDERID AND OP.HVR_ISDELETE = 0
INNER JOIN CDC_ORION.BROKER.REFERENCE_NUMBER AS RN ON RN.FOREIGNID = OP.ORDERPARTYID AND RN.ENTITYID = 2 AND RN.HVR_ISDELETE = 0 --CUSTOMER
INNER JOIN CDC_REFERENCEDATA.BROKER.REF_REFDATA AS REF ON REF.REFDATANUMBER = RN.REFERENCEDATANUMBER AND RN.HVR_ISDELETE = 0
INNER JOIN CDC_MDM.BROKER.MDM_PARTY AS MDM ON MDM.PARTYNUMBER = OP.PARTYNUMBER AND MDM.HVR_ISDELETE = 0
INNER JOIN CDC_ORION.BROKER.REFERENCE_ENTITY AS RE ON RE.ENTITYID = RN.ENTITYID AND RE.HVR_ISDELETE = 0
WHERE A.HVR_ISDELETE = 0
and a.createdatetime >= {startdate}

union

SELECT
A.LOADNUMBER
,MDM.PARTYCODE::string partycode
,A.ORDERNUMBER::string AS REFNUM
FROM CDC_ORION.BROKER.EP_ACTIVITY AS A 
INNER JOIN CDC_ORION.BROKER.CO_ORDER AS O ON O.CUSTOMERORDERNUMBER = A.ORDERNUMBER AND O.HVR_ISDELETE = 0
INNER JOIN CDC_ORION.BROKER.CO_ORDERPARTY AS OP ON OP.CUSTOMERORDERID = O.CUSTOMERORDERID AND OP.HVR_ISDELETE = 0
INNER JOIN CDC_ORION.BROKER.REFERENCE_NUMBER AS RN ON RN.FOREIGNID = OP.ORDERPARTYID AND RN.ENTITYID = 2 AND RN.HVR_ISDELETE = 0 --CUSTOMER
INNER JOIN CDC_REFERENCEDATA.BROKER.REF_REFDATA AS REF ON REF.REFDATANUMBER = RN.REFERENCEDATANUMBER AND RN.HVR_ISDELETE = 0
INNER JOIN CDC_MDM.BROKER.MDM_PARTY AS MDM ON MDM.PARTYNUMBER = OP.PARTYNUMBER AND MDM.HVR_ISDELETE = 0
INNER JOIN CDC_ORION.BROKER.REFERENCE_ENTITY AS RE ON RE.ENTITYID = RN.ENTITYID AND RE.HVR_ISDELETE = 0
WHERE A.HVR_ISDELETE = 0
and a.createdatetime >= {startdate}

union

select distinct * from (
SELECT
A.LOADNUMBER
,MDM.PARTYCODE::string partycode
,A.loadnumber::string REFNUM
FROM CDC_ORION.BROKER.EP_ACTIVITY AS A 
INNER JOIN CDC_ORION.BROKER.CO_ORDER AS O ON O.CUSTOMERORDERNUMBER = A.ORDERNUMBER AND O.HVR_ISDELETE = 0
INNER JOIN CDC_ORION.BROKER.CO_ORDERPARTY AS OP ON OP.CUSTOMERORDERID = O.CUSTOMERORDERID AND OP.HVR_ISDELETE = 0
INNER JOIN CDC_ORION.BROKER.REFERENCE_NUMBER AS RN ON RN.FOREIGNID = OP.ORDERPARTYID AND RN.ENTITYID = 2 AND RN.HVR_ISDELETE = 0 --CUSTOMER
INNER JOIN CDC_REFERENCEDATA.BROKER.REF_REFDATA AS REF ON REF.REFDATANUMBER = RN.REFERENCEDATANUMBER AND RN.HVR_ISDELETE = 0
INNER JOIN CDC_MDM.BROKER.MDM_PARTY AS MDM ON MDM.PARTYNUMBER = OP.PARTYNUMBER AND MDM.HVR_ISDELETE = 0
INNER JOIN CDC_ORION.BROKER.REFERENCE_ENTITY AS RE ON RE.ENTITYID = RN.ENTITYID AND RE.HVR_ISDELETE = 0
WHERE A.HVR_ISDELETE = 0
and a.createdatetime >= {startdate}) a
)

select * from reference_data where loadnumber is not null