with reference_data_working as
(SELECT
A.LOADNUMBER
,MDM.PARTYCODE::string partycode
,MDM.name::string partyname
,RN.VALUE::string AS REFNUM
FROM CDC_ORION.BROKER.EP_ACTIVITY AS A 
INNER JOIN CDC_ORION.BROKER.CO_ORDER AS O ON O.CUSTOMERORDERNUMBER = A.ORDERNUMBER AND O.HVR_ISDELETE = 0
INNER JOIN CDC_ORION.BROKER.CO_ORDERPARTY AS OP ON OP.CUSTOMERORDERID = O.CUSTOMERORDERID AND OP.HVR_ISDELETE = 0
INNER JOIN CDC_ORION.BROKER.REFERENCE_NUMBER AS RN ON RN.FOREIGNID = OP.ORDERPARTYID AND RN.ENTITYID = 2 AND RN.HVR_ISDELETE = 0 --CUSTOMER
-- INNER JOIN CDC_REFERENCEDATA.BROKER.REF_REFDATA AS REF ON REF.REFDATANUMBER = RN.REFERENCEDATANUMBER AND RN.HVR_ISDELETE = 0
INNER JOIN CDC_MDM.BROKER.MDM_PARTY AS MDM ON MDM.PARTYNUMBER = OP.PARTYNUMBER AND MDM.HVR_ISDELETE = 0
-- INNER JOIN CDC_ORION.BROKER.REFERENCE_ENTITY AS RE ON RE.ENTITYID = RN.ENTITYID AND RE.HVR_ISDELETE = 0
WHERE A.HVR_ISDELETE = 0
and MDM.PARTYCODE like 'C%'
and a.createdatetime >= {startdate}

union

SELECT
A.LOADNUMBER
,MDM.PARTYCODE::string partycode
,MDM.name::string partyname
,A.ORDERNUMBER::string AS REFNUM
FROM CDC_ORION.BROKER.EP_ACTIVITY AS A 
INNER JOIN CDC_ORION.BROKER.CO_ORDER AS O ON O.CUSTOMERORDERNUMBER = A.ORDERNUMBER AND O.HVR_ISDELETE = 0
INNER JOIN CDC_ORION.BROKER.CO_ORDERPARTY AS OP ON OP.CUSTOMERORDERID = O.CUSTOMERORDERID AND OP.HVR_ISDELETE = 0
-- INNER JOIN CDC_ORION.BROKER.REFERENCE_NUMBER AS RN ON RN.FOREIGNID = OP.ORDERPARTYID AND RN.ENTITYID = 2 AND RN.HVR_ISDELETE = 0 --CUSTOMER
-- INNER JOIN CDC_REFERENCEDATA.BROKER.REF_REFDATA AS REF ON REF.REFDATANUMBER = RN.REFERENCEDATANUMBER AND RN.HVR_ISDELETE = 0
INNER JOIN CDC_MDM.BROKER.MDM_PARTY AS MDM ON MDM.PARTYNUMBER = OP.PARTYNUMBER AND MDM.HVR_ISDELETE = 0
-- INNER JOIN CDC_ORION.BROKER.REFERENCE_ENTITY AS RE ON RE.ENTITYID = RN.ENTITYID AND RE.HVR_ISDELETE = 0
WHERE A.HVR_ISDELETE = 0
and MDM.PARTYCODE like 'C%'
and a.createdatetime >= {startdate}

union

select distinct * from (
SELECT
A.LOADNUMBER
,MDM.PARTYCODE::string partycode
,MDM.name::string partyname
,A.loadnumber::string REFNUM
FROM CDC_ORION.BROKER.EP_ACTIVITY AS A 
INNER JOIN CDC_ORION.BROKER.CO_ORDER AS O ON O.CUSTOMERORDERNUMBER = A.ORDERNUMBER AND O.HVR_ISDELETE = 0
INNER JOIN CDC_ORION.BROKER.CO_ORDERPARTY AS OP ON OP.CUSTOMERORDERID = O.CUSTOMERORDERID AND OP.HVR_ISDELETE = 0
-- INNER JOIN CDC_ORION.BROKER.REFERENCE_NUMBER AS RN ON RN.FOREIGNID = OP.ORDERPARTYID AND RN.ENTITYID = 2 AND RN.HVR_ISDELETE = 0 --CUSTOMER
-- INNER JOIN CDC_REFERENCEDATA.BROKER.REF_REFDATA AS REF ON REF.REFDATANUMBER = RN.REFERENCEDATANUMBER AND RN.HVR_ISDELETE = 0
INNER JOIN CDC_MDM.BROKER.MDM_PARTY AS MDM ON MDM.PARTYNUMBER = OP.PARTYNUMBER AND MDM.HVR_ISDELETE = 0
-- INNER JOIN CDC_ORION.BROKER.REFERENCE_ENTITY AS RE ON RE.ENTITYID = RN.ENTITYID AND RE.HVR_ISDELETE = 0
WHERE A.HVR_ISDELETE = 0
and MDM.PARTYCODE like 'C%'
and a.createdatetime >= {startdate}) a
)

,reference_data as 
(
select rdw.*, lb.carrier_code, p.name carrier_name
from reference_data_working rdw
inner join nast_carrier_domain.broker.load_books lb on lb.load_num = rdw.loadnumber and bounced = False and nast_truckload_flag = True
left join cdc_mdm.broker.mdm_party p on p.partycode = lb.carrier_code
inner join cdc_mdm.broker.mdm_partytype pt on pt.partytypeid = p.partytypeid and pt.description = 'Carriers' -- filtering to just party types of carriers (in case any non carriers are listed as carriers)
qualify count(distinct carrier_code) over (partition by loadnumber) = 1
)

select * from reference_data where loadnumber is not null